#############################################################################
# Makefile for building: test_network
# Generated by qmake (2.01a) (Qt 4.7.1) on: Wed May 6 03:58:33 2015
# Project:  test_network.pro
# Template: app
# Command: /root/qt-everywhere-opensource-src-4.7.1/qt-everywhere-opensource-src-4.7.1/bin/qmake -spec /opt/qt-4.7.1/mkspecs/qws/linux-arm-g++ -o Makefile test_network.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-linux-gcc
CXX           = arm-linux-g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/qt-4.7.1/mkspecs/qws/linux-arm-g++ -I. -I/opt/qt-4.7.1/include/QtCore -I/opt/qt-4.7.1/include/QtNetwork -I/opt/qt-4.7.1/include/QtGui -I/opt/qt-4.7.1/include -I. -I.
LINK          = arm-linux-g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/opt/qt-4.7.1/lib
LIBS          = $(SUBLIBS)  -L/opt/qt-4.7.1/lib -lQtGui -L/usr/local/tslib/lib -L/opt/qt-4.7.1/lib -lQtNetwork -lQtCore -lpthread 
AR            = arm-linux-ar cqs
RANLIB        = 
QMAKE         = /root/qt-everywhere-opensource-src-4.7.1/qt-everywhere-opensource-src-4.7.1/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-linux-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		widget.cpp \
		videodevice.cpp \
		camera.cpp \
		udp.cpp \
		mythread.cpp \
		mainwindow.cpp \
		client.cpp moc_widget.cpp \
		moc_videodevice.cpp \
		moc_camera.cpp \
		moc_udp.cpp \
		moc_mythread.cpp \
		moc_mainwindow.cpp \
		moc_client.cpp
OBJECTS       = main.o \
		widget.o \
		videodevice.o \
		camera.o \
		udp.o \
		mythread.o \
		mainwindow.o \
		client.o \
		moc_widget.o \
		moc_videodevice.o \
		moc_camera.o \
		moc_udp.o \
		moc_mythread.o \
		moc_mainwindow.o \
		moc_client.o
DIST          = /opt/qt-4.7.1/mkspecs/common/g++.conf \
		/opt/qt-4.7.1/mkspecs/common/unix.conf \
		/opt/qt-4.7.1/mkspecs/common/linux.conf \
		/opt/qt-4.7.1/mkspecs/common/qws.conf \
		/opt/qt-4.7.1/mkspecs/qconfig.pri \
		/opt/qt-4.7.1/mkspecs/features/qt_functions.prf \
		/opt/qt-4.7.1/mkspecs/features/qt_config.prf \
		/opt/qt-4.7.1/mkspecs/features/exclusive_builds.prf \
		/opt/qt-4.7.1/mkspecs/features/default_pre.prf \
		/opt/qt-4.7.1/mkspecs/features/release.prf \
		/opt/qt-4.7.1/mkspecs/features/default_post.prf \
		/opt/qt-4.7.1/mkspecs/features/warn_on.prf \
		/opt/qt-4.7.1/mkspecs/features/qt.prf \
		/opt/qt-4.7.1/mkspecs/features/unix/thread.prf \
		/opt/qt-4.7.1/mkspecs/features/moc.prf \
		/opt/qt-4.7.1/mkspecs/features/resources.prf \
		/opt/qt-4.7.1/mkspecs/features/uic.prf \
		/opt/qt-4.7.1/mkspecs/features/yacc.prf \
		/opt/qt-4.7.1/mkspecs/features/lex.prf \
		/opt/qt-4.7.1/mkspecs/features/include_source_dir.prf \
		test_network.pro
QMAKE_TARGET  = test_network
DESTDIR       = 
TARGET        = test_network

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_widget.h ui_camera.h ui_mainwindow.h ui_client.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: test_network.pro  /opt/qt-4.7.1/mkspecs/qws/linux-arm-g++/qmake.conf /opt/qt-4.7.1/mkspecs/common/g++.conf \
		/opt/qt-4.7.1/mkspecs/common/unix.conf \
		/opt/qt-4.7.1/mkspecs/common/linux.conf \
		/opt/qt-4.7.1/mkspecs/common/qws.conf \
		/opt/qt-4.7.1/mkspecs/qconfig.pri \
		/opt/qt-4.7.1/mkspecs/features/qt_functions.prf \
		/opt/qt-4.7.1/mkspecs/features/qt_config.prf \
		/opt/qt-4.7.1/mkspecs/features/exclusive_builds.prf \
		/opt/qt-4.7.1/mkspecs/features/default_pre.prf \
		/opt/qt-4.7.1/mkspecs/features/release.prf \
		/opt/qt-4.7.1/mkspecs/features/default_post.prf \
		/opt/qt-4.7.1/mkspecs/features/warn_on.prf \
		/opt/qt-4.7.1/mkspecs/features/qt.prf \
		/opt/qt-4.7.1/mkspecs/features/unix/thread.prf \
		/opt/qt-4.7.1/mkspecs/features/moc.prf \
		/opt/qt-4.7.1/mkspecs/features/resources.prf \
		/opt/qt-4.7.1/mkspecs/features/uic.prf \
		/opt/qt-4.7.1/mkspecs/features/yacc.prf \
		/opt/qt-4.7.1/mkspecs/features/lex.prf \
		/opt/qt-4.7.1/mkspecs/features/include_source_dir.prf \
		/opt/qt-4.7.1/lib/libQtGui.prl \
		/opt/qt-4.7.1/lib/libQtNetwork.prl \
		/opt/qt-4.7.1/lib/libQtCore.prl
	$(QMAKE) -spec /opt/qt-4.7.1/mkspecs/qws/linux-arm-g++ -o Makefile test_network.pro
/opt/qt-4.7.1/mkspecs/common/g++.conf:
/opt/qt-4.7.1/mkspecs/common/unix.conf:
/opt/qt-4.7.1/mkspecs/common/linux.conf:
/opt/qt-4.7.1/mkspecs/common/qws.conf:
/opt/qt-4.7.1/mkspecs/qconfig.pri:
/opt/qt-4.7.1/mkspecs/features/qt_functions.prf:
/opt/qt-4.7.1/mkspecs/features/qt_config.prf:
/opt/qt-4.7.1/mkspecs/features/exclusive_builds.prf:
/opt/qt-4.7.1/mkspecs/features/default_pre.prf:
/opt/qt-4.7.1/mkspecs/features/release.prf:
/opt/qt-4.7.1/mkspecs/features/default_post.prf:
/opt/qt-4.7.1/mkspecs/features/warn_on.prf:
/opt/qt-4.7.1/mkspecs/features/qt.prf:
/opt/qt-4.7.1/mkspecs/features/unix/thread.prf:
/opt/qt-4.7.1/mkspecs/features/moc.prf:
/opt/qt-4.7.1/mkspecs/features/resources.prf:
/opt/qt-4.7.1/mkspecs/features/uic.prf:
/opt/qt-4.7.1/mkspecs/features/yacc.prf:
/opt/qt-4.7.1/mkspecs/features/lex.prf:
/opt/qt-4.7.1/mkspecs/features/include_source_dir.prf:
/opt/qt-4.7.1/lib/libQtGui.prl:
/opt/qt-4.7.1/lib/libQtNetwork.prl:
/opt/qt-4.7.1/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/qt-4.7.1/mkspecs/qws/linux-arm-g++ -o Makefile test_network.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/test_network1.0.0 || $(MKDIR) .tmp/test_network1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/test_network1.0.0/ && $(COPY_FILE) --parents widget.h videodevice.h camera.h udp.h mythread.h config.h mainwindow.h client.h .tmp/test_network1.0.0/ && $(COPY_FILE) --parents main.cpp widget.cpp videodevice.cpp camera.cpp udp.cpp mythread.cpp mainwindow.cpp client.cpp .tmp/test_network1.0.0/ && $(COPY_FILE) --parents widget.ui camera.ui mainwindow.ui client.ui .tmp/test_network1.0.0/ && (cd `dirname .tmp/test_network1.0.0` && $(TAR) test_network1.0.0.tar test_network1.0.0 && $(COMPRESS) test_network1.0.0.tar) && $(MOVE) `dirname .tmp/test_network1.0.0`/test_network1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/test_network1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_widget.cpp moc_videodevice.cpp moc_camera.cpp moc_udp.cpp moc_mythread.cpp moc_mainwindow.cpp moc_client.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_widget.cpp moc_videodevice.cpp moc_camera.cpp moc_udp.cpp moc_mythread.cpp moc_mainwindow.cpp moc_client.cpp
moc_widget.cpp: camera.h \
		videodevice.h \
		widget.h \
		udp.h \
		mythread.h \
		config.h \
		widget.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) widget.h -o moc_widget.cpp

moc_videodevice.cpp: widget.h \
		camera.h \
		videodevice.h \
		config.h \
		udp.h \
		mythread.h \
		videodevice.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) videodevice.h -o moc_videodevice.cpp

moc_camera.cpp: videodevice.h \
		widget.h \
		camera.h \
		config.h \
		udp.h \
		mythread.h \
		camera.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) camera.h -o moc_camera.cpp

moc_udp.cpp: widget.h \
		camera.h \
		videodevice.h \
		config.h \
		udp.h \
		mythread.h \
		udp.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) udp.h -o moc_udp.cpp

moc_mythread.cpp: videodevice.h \
		widget.h \
		camera.h \
		config.h \
		udp.h \
		mythread.h \
		mythread.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) mythread.h -o moc_mythread.cpp

moc_mainwindow.cpp: widget.h \
		camera.h \
		videodevice.h \
		config.h \
		udp.h \
		mythread.h \
		client.h \
		mainwindow.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_client.cpp: udp.h \
		widget.h \
		camera.h \
		videodevice.h \
		config.h \
		mythread.h \
		client.h
	/opt/qt-4.7.1/bin/moc $(DEFINES) $(INCPATH) client.h -o moc_client.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_widget.h ui_camera.h ui_mainwindow.h ui_client.h
compiler_uic_clean:
	-$(DEL_FILE) ui_widget.h ui_camera.h ui_mainwindow.h ui_client.h
ui_widget.h: widget.ui
	/opt/qt-4.7.1/bin/uic widget.ui -o ui_widget.h

ui_camera.h: camera.ui
	/opt/qt-4.7.1/bin/uic camera.ui -o ui_camera.h

ui_mainwindow.h: mainwindow.ui
	/opt/qt-4.7.1/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_client.h: client.ui
	/opt/qt-4.7.1/bin/uic client.ui -o ui_client.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		widget.h \
		camera.h \
		videodevice.h \
		config.h \
		udp.h \
		mythread.h \
		client.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

widget.o: widget.cpp widget.h \
		camera.h \
		videodevice.h \
		config.h \
		udp.h \
		mythread.h \
		ui_widget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

videodevice.o: videodevice.cpp videodevice.h \
		widget.h \
		camera.h \
		config.h \
		udp.h \
		mythread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o videodevice.o videodevice.cpp

camera.o: camera.cpp camera.h \
		videodevice.h \
		widget.h \
		udp.h \
		mythread.h \
		config.h \
		ui_camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o camera.o camera.cpp

udp.o: udp.cpp udp.h \
		widget.h \
		camera.h \
		videodevice.h \
		config.h \
		mythread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o udp.o udp.cpp

mythread.o: mythread.cpp mythread.h \
		videodevice.h \
		widget.h \
		camera.h \
		config.h \
		udp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mythread.o mythread.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		widget.h \
		camera.h \
		videodevice.h \
		config.h \
		udp.h \
		mythread.h \
		client.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

client.o: client.cpp client.h \
		udp.h \
		widget.h \
		camera.h \
		videodevice.h \
		config.h \
		mythread.h \
		ui_client.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o client.o client.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

moc_videodevice.o: moc_videodevice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_videodevice.o moc_videodevice.cpp

moc_camera.o: moc_camera.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_camera.o moc_camera.cpp

moc_udp.o: moc_udp.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_udp.o moc_udp.cpp

moc_mythread.o: moc_mythread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mythread.o moc_mythread.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_client.o: moc_client.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_client.o moc_client.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

